# .prettierrc
printWidth: 100
# tabWidth: 4
# useTabs: false
semi: true
singleQuote: true
# arrowParens: "avoid"
# bracketSpacing: true
jsxBracketSameLine: false
proseWrap: 'preserve'
# trailingComma: "es5"

